sec_edgar_bq:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth            # <- use ADC (metadata on Cloud Run, GH OIDC/SA_JSON in Actions)
      project: "{{ env_var('GCP_PROJECT_ID','sec-edgar-financials-warehouse') }}"
      dataset: "{{ env_var('BQ_CURATED_DATASET','sec_curated') }}"
      location: "{{ env_var('BQ_LOCATION','US') }}"
      threads: 4
      # no keyfile / no keyfile_json here
