name: schedule-run
on:
  schedule:
    - cron: "0 6 * * *"  # daily 06:00 UTC
  workflow_dispatch:

jobs:
  run-sec-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Execute Cloud Run Job
        run: |
          gcloud config set project sec-edgar-financials-warehouse
          gcloud run jobs execute sec-pipeline-job --region us-central1